<script setup>
// import MainContent from '@/components/content/MainContent.vue'
import MainContent from '@/components/content/MainContent.vue'
import SideBar from '@/components/content/SideBar.vue'
import FooterNav from '@/components/FooterNav.vue'
import NavBar from '@/components/NavBar.vue'
import NavOptions from '@/components/NavOptions.vue'
import { useContent } from '@/stores/content'
// import { ref } from 'vue'

const content = useContent()

content.fetchData() // Fetch data when the component mounts
</script>

<template>
  <!-- X side bar -->
  <!-- <pre class="text-black">{{ content.data.posts[0] }}</pre> -->
  <main class="flex justify-center w-screen">
    <div class="relative max-w-md bg-black h-100vh border rounded-xl">
      <Transition name="mac">
        <SideBar v-show="content.showSideBar" class="absolute" />
      </Transition>
      <div class="flex flex-col justify-between w-[448px] h-screen hide-scrollbars">
        <div class="flex flex-col">
          <!-- X-Navigation bar -->
          <NavBar />
          <!-- X-Navigation bar Options -->
          <NavOptions />
          <!-- Main content -->
          <div class="h-[430px] text-white">
            <MainContent :authors="content.data.posts" />
          </div>
        </div>
        <!-- Create a footer nav for the X app -->
        <FooterNav />
      </div>
    </div>
  </main>
</template>

<style scoped>
.hide-scrollbars {
  overflow: hidden; /* Hide overflow scrollbars completely */
  overflow-y: scroll; /* Enable vertical scrolling without showing scrollbar */
  overflow-x: scroll; /* Enable horizontal scrolling without showing scrollbar */

  /* Hide scrollbar for Chrome, Safari, and Opera */
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* Internet Explorer 10+ */
}

/* Hide scrollbar for WebKit browsers */
.hide-scrollbars::-webkit-scrollbar {
  display: none;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 1s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.slide-enter-active, .slide-leave-active {
  transition: transform 0.5s ease;

}
.slide-enter-from {
  transform: translateX(-100%);

}
.slide-leave-to {
  transform: translateX(-100%);
}

/* Keyframes for bounce effect */
@keyframes bounce {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-20px);
  }
}

/* Enter and leave animations */
.bounce-enter-active, .bounce-leave-active {
  animation: bounce 5s ease;
}


/* Keyframes for rotation */
@keyframes rotate {
  0% {
    transform: rotate(0deg);
    opacity: 1;
  }
  50% {
    transform: rotate(360deg);
    opacity: 0;
  }
  100% {
    transform: rotate(360deg);
    opacity: 1;
  }
}

/* Enter and leave animations */
.rotate-enter-active, .rotate-leave-active {
  animation: rotate 1s ease-in reverse;
}
/* Make the reverse of the rotate animation */
.rotate-enter-active {
  animation: rotate 1s ease-in;
  }

/* Keyframes for scaling */
@keyframes scale {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}

/* Enter and leave animations */
.scale-enter-active {
  animation: scale 0.5s ease;
}
.scale-leave-active {
  animation: scale 0.5s ease reverse
}

/* Keyframes for the minimize/maximize effect */
@keyframes minimize {
  0% {
    transform: scale(1) translateY(0);
    opacity: 1;
  }
  100% {
    transform: scale(0.1) translateY(300px);
    opacity: 0;
  }
}

@keyframes maximize {
  0% {
    transform: scale(0.1) translateY(300px);
    opacity: 0;
  }
  100% {
    transform: scale(1) translateY(0);
    opacity: 1;
  }
}

/* Enter and leave animations */
.mac-enter-active {
  animation: maximize 0.5s ease-out forwards;
}
.mac-leave-active {
  animation: minimize 0.5s ease-in forwards;
}

/* Styling for the animated element */
.mac-element {
  width: 300px;
  height: 200px;
  background: linear-gradient(135deg, #4facfe, #00f2fe);
  color: white;
  font-size: 16px;
  font-weight: bold;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 12px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
}



.flip-scale-up-diag-1-enter-active {
  -webkit-animation: flip-scale-up-diag-1 0.5s linear both;
  animation: flip-scale-up-diag-1 0.5s linear both;
}
.flip-scale-up-diag-1-leave-active {
  -webkit-animation: flip-scale-up-diag-1 0.5s linear both reverse;
  animation: flip-scale-up-diag-1 0.5s linear both reverse
}
/* ----------------------------------------------
 * Generated by Animista on 2024-11-15 11:16:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-up-diag-1
 * ----------------------------------------
 */
 @-webkit-keyframes flip-scale-up-diag-1 {
  0% {
    -webkit-transform: scale(1) rotate3d(1, 1, 0, 0deg);
            transform: scale(1) rotate3d(1, 1, 0, 0deg);
  }
  50% {
    -webkit-transform: scale(2.5) rotate3d(1, 1, 0, 90deg);
            transform: scale(2.5) rotate3d(1, 1, 0, 90deg);
  }
  100% {
    -webkit-transform: scale(1) rotate3d(1, 1, 0, 180deg);
            transform: scale(1) rotate3d(1, 1, 0, 180deg);
  }
}
@keyframes flip-scale-up-diag-1 {
  0% {
    -webkit-transform: scale(1) rotate3d(1, 1, 0, 0deg);
            transform: scale(1) rotate3d(1, 1, 0, 0deg);
  }
  50% {
    -webkit-transform: scale(2.5) rotate3d(1, 1, 0, 90deg);
            transform: scale(2.5) rotate3d(1, 1, 0, 90deg);
  }
  100% {
    -webkit-transform: scale(1) rotate3d(1, 1, 0, 180deg);
            transform: scale(1) rotate3d(1, 1, 0, 180deg);
  }
}

</style>
